/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author USER
 */
public class formutama extends javax.swing.JFrame {

    /**
     * Creates new form formutama
     */
    public formutama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
   private void setEnableMenu(boolean aktif) {
    datamenu.setEnabled(aktif);
    transaksimenu.setEnabled(aktif);
    laporanmenu.setEnabled(aktif);
   }
   
   private void setUkuranLokasiFrame(double skala, boolean tengah) {
    Dimension dimensi = Toolkit.getDefaultToolkit().getScreenSize();
    setSize((int) (skala * dimensi.getWidth()), (int) (skala * dimensi.getHeight()));

    if (tengah) {
        setLocation((int) ((dimensi.getWidth() - getWidth()) / 2),
                    (int) ((dimensi.getHeight() - getHeight()) / 2));
    }
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mdiDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        aplikasimenu = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        deskripsiMenu = new javax.swing.JMenuItem();
        aksesMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        keluarMenu = new javax.swing.JMenuItem();
        datamenu = new javax.swing.JMenu();
        karyawanMenuItem = new javax.swing.JMenuItem();
        pekerjaanMenuItem = new javax.swing.JMenuItem();
        transaksimenu = new javax.swing.JMenu();
        gajiMenuItem = new javax.swing.JMenuItem();
        laporanmenu = new javax.swing.JMenu();
        gajiMenuLaporan = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        karyawanMenuLaporan = new javax.swing.JMenuItem();
        pekerjaanMenuLaporan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout mdiDesktopPaneLayout = new javax.swing.GroupLayout(mdiDesktopPane);
        mdiDesktopPane.setLayout(mdiDesktopPaneLayout);
        mdiDesktopPaneLayout.setHorizontalGroup(
            mdiDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        mdiDesktopPaneLayout.setVerticalGroup(
            mdiDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        aplikasimenu.setText("APLIKASI");
        aplikasimenu.add(jSeparator1);

        deskripsiMenu.setText("Deskripsi");
        aplikasimenu.add(deskripsiMenu);

        aksesMenu.setText("Login");
        aplikasimenu.add(aksesMenu);
        aplikasimenu.add(jSeparator2);

        keluarMenu.setText("Keluar");
        keluarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarMenuActionPerformed(evt);
            }
        });
        aplikasimenu.add(keluarMenu);

        jMenuBar1.add(aplikasimenu);

        datamenu.setText("MASTER DATA");

        karyawanMenuItem.setText("Karyawan");
        datamenu.add(karyawanMenuItem);

        pekerjaanMenuItem.setText("Pekerjaan");
        datamenu.add(pekerjaanMenuItem);

        jMenuBar1.add(datamenu);

        transaksimenu.setText("TRANSAKSI");

        gajiMenuItem.setText("Gaji");
        transaksimenu.add(gajiMenuItem);

        jMenuBar1.add(transaksimenu);

        laporanmenu.setText("LAPORAN");

        gajiMenuLaporan.setText("Gaji");
        laporanmenu.add(gajiMenuLaporan);
        laporanmenu.add(jSeparator3);

        karyawanMenuLaporan.setText("Karyawan");
        laporanmenu.add(karyawanMenuLaporan);

        pekerjaanMenuLaporan.setText("Pekerjaan");
        laporanmenu.add(pekerjaanMenuLaporan);

        jMenuBar1.add(laporanmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarMenuActionPerformed
    System.exit(0);     
    }//GEN-LAST:event_keluarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formutama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aksesMenu;
    private javax.swing.JMenu aplikasimenu;
    private javax.swing.JMenu datamenu;
    private javax.swing.JMenuItem deskripsiMenu;
    private javax.swing.JMenuItem gajiMenuItem;
    private javax.swing.JMenuItem gajiMenuLaporan;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem karyawanMenuItem;
    private javax.swing.JMenuItem karyawanMenuLaporan;
    private javax.swing.JMenuItem keluarMenu;
    private javax.swing.JMenu laporanmenu;
    private javax.swing.JDesktopPane mdiDesktopPane;
    private javax.swing.JMenuItem pekerjaanMenuItem;
    private javax.swing.JMenuItem pekerjaanMenuLaporan;
    private javax.swing.JMenu transaksimenu;
    // End of variables declaration//GEN-END:variables
}
